name: Ruby

on:
  push:

jobs:
  todo:
    runs-on: ubuntu-latest

    name: Todo
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Bundle install
        run: bundle install
      - name: Run Todo Search
        run: ./exe/grepfruit s -r 'TODO' -e 'vendor,.yardoc,.git,ci.yml:22,README.md,spec/grepfruit/search_spec.rb,spec/test_dataset' --search-hidden


  linting:
    runs-on: ubuntu-latest

    name: RuboCop
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Bundle install
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop --color

  tests:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }}
    permissions:
      contents: read
    strategy:
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          # TODO: ruby 4
          - "4.0.0-preview3"

    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: bundle install
      - name: Run RSpec
        run: bundle exec rspec
